export const WORKSPACE_PERMISSIONS = Object.freeze({
  READ_WORKSPACE: "READ_WORKSPACE",
  UPDATE_WORKSPACE: "UPDATE_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  MANAGE_MEMBERS: "MANAGE_MEMBERS",
  CREATE_PROJECT: "CREATE_PROJECT",
});

export const PROJECT_PERMISSIONS = Object.freeze({
  READ_PROJECT: "READ_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  MANAGE_MEMBERS: "MANAGE_MEMBERS",
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
});