import {
  PROJECT_PERMISSIONS,
  PROJECT_ROLES,
} from "../constants/access.js";

const rolePermissions =
  Object.freeze({
    [PROJECT_ROLES.OWNER]: [
      PROJECT_PERMISSIONS.READ_PROJECT,
      PROJECT_PERMISSIONS.UPDATE_PROJECT,
      PROJECT_PERMISSIONS.DELETE_PROJECT,
      PROJECT_PERMISSIONS.MANAGE_MEMBERS,
      PROJECT_PERMISSIONS.CREATE_TASK,
      PROJECT_PERMISSIONS.UPDATE_TASK,
      PROJECT_PERMISSIONS.DELETE_TASK,
    ],

    [PROJECT_ROLES.CONTRIBUTOR]: [
      PROJECT_PERMISSIONS.READ_PROJECT,
      PROJECT_PERMISSIONS.CREATE_TASK,
      PROJECT_PERMISSIONS.UPDATE_TASK,
      PROJECT_PERMISSIONS.DELETE_TASK,
    ],

    [PROJECT_ROLES.REVIEWER]: [
      PROJECT_PERMISSIONS.READ_PROJECT,
    ],
  });

export function getProjectPermissions(
  role,
) {
  return rolePermissions[role] ?? [];
}