import {
  WORKSPACE_PERMISSIONS,
  WORKSPACE_ROLES,
} from "../constants/access.js";

const rolePermissions =
  Object.freeze({
    [WORKSPACE_ROLES.OWNER]: [
      WORKSPACE_PERMISSIONS.READ_WORKSPACE,
      WORKSPACE_PERMISSIONS.UPDATE_WORKSPACE,
      WORKSPACE_PERMISSIONS.DELETE_WORKSPACE,
      WORKSPACE_PERMISSIONS.MANAGE_MEMBERS,
      WORKSPACE_PERMISSIONS.CREATE_PROJECT,
    ],

    [WORKSPACE_ROLES.ADMIN]: [
      WORKSPACE_PERMISSIONS.READ_WORKSPACE,
      WORKSPACE_PERMISSIONS.UPDATE_WORKSPACE,
      WORKSPACE_PERMISSIONS.MANAGE_MEMBERS,
      WORKSPACE_PERMISSIONS.CREATE_PROJECT,
    ],

    [WORKSPACE_ROLES.MEMBER]: [
      WORKSPACE_PERMISSIONS.READ_WORKSPACE,
      WORKSPACE_PERMISSIONS.CREATE_PROJECT,
    ],

    [WORKSPACE_ROLES.GUEST]: [
      WORKSPACE_PERMISSIONS.READ_WORKSPACE,
    ],
  });

export function getWorkspacePermissions(
  role,
) {
  return rolePermissions[role] ?? [];
}